application: municipalithree
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: municipalithree.wsgi.application

libraries:
- name: django
  version: "1.4"
- name: PIL
  version: "latest"
